version: '3.7'

services:
  nepvoice-database:
    image: ankane/pgvector:latest 
    environment:
      POSTGRES_USER: nepvoice
      POSTGRES_PASSWORD: nepvoice
      POSTGRES_DB: nepvoice
    ports:
      - "9090:5432"
    networks:
      - app-network
    restart: always
    volumes:
      - ./nepvoice-db:/var/lib/postgresql/data

  nepvoice-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    depends_on:
      - nepvoice-database
    volumes:
      - ./backend:/backend
      - ./files:/files

    networks:
      - app-network
    restart: always

  

networks:
  app-network:
    driver: bridge
