version: '3.7'

services:
  nepvoice-database:
    image: ankane/pgvector:latest 
    environment:
      POSTGRES_USER: nepvoice
      POSTGRES_PASSWORD: nepvoice
      POSTGRES_DB: nepvoice
    ports:
      - "9090:5432"
    networks:
      - app-network
    restart: always
    volumes:
      - ./nepvoice-db:/var/lib/postgresql/data

  nepvoice-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: nepvoice-backend
    ports:
      - "5678:5678"
    depends_on:
      - nepvoice-database
    volumes:
      - ./backend:/backend
      - ./files:/files
      - ./asr_audios:/asr_audios
      - ./tts_audios:/tts_audios
    networks:
      - app-network
    restart: always

  nepvoice-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nepvoice-frontend
    restart: always
    ports:
      - 5679:8001
    environment:
      - BACKEND=https://nepvoice-backend.wiseyak.com
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
