
# OAuth Config
CLIENT_ID = ''
CLIENT_SECRET = ''
REDIRECT_URI = ''
AUTH_URI = ''
TOKEN_URI = ''
USERINFO_URI = ''

SECRET_KEY = "3f7b9c3f60dc4a1e4f56849a9c12f4b9" 
ALGORITHM = "HS256" # 

POSTGRES_USER='nepvoice'
POSTGRES_PASSWORD='nepvoice'
POSTGRES_HOST='nepvoice-database'
POSTGRES_PORT=5432
POSTGRES_DB='nepvoice'